package.json, vue.config.js
=> Change: package.json, vue.config.js

package.json
- - build에 '--watch' 옵션 때문에 vercel에서 무한 로딩
- build에 '--watch' 옵션 제거
=> Change: package.json

src/components/project/CardCompo.vue, src/components/project/ProjectRecruitment.vue
=> Design_create_project

src/components/MemberCard.vue, src/components/project-detail/LeaderInfo.vue, src/components/project-detail/ProjectInfo.vue, src/components/project-detail/RecruitmentStatus.vue, src/components/project-detail/TechStack.vue
=> feat/jy/project-detail: 프로젝트 상세 페이지 UI 및 props 추가

src/common/FooterLayout.vue, src/components/project-detail/ProjectDescription.vue, src/components/project-detail/ProjectMembers.vue, src/components/project-detail/RecruitmentStatus.vue
- Footer의 색상 변경
- 프로젝트 설명에서 html을 랜더링하도록 수정
- 프로젝트에 참여한 멤버가 없는 경우 '아직 참여 중인 멤버가 없어요.' 문구 출력
- 지원 하기 버튼 랜더링 조건 변경
=> Design: UI 디자인 변경

src/components/commonModal/CommonModal.vue, src/components/project/ProjectTest.vue, src/main.js, src/plugins/axios_custom.js
* [내용 정리](https://share.note.sx/ir12vgu9#HLq3hvaXW0qUYA/+Rl7rul3lEvocHZrBpmwj+1vV6vc)
=> feat_AxiosInterceptor

src/components/project-detail/ProjectManagement.vue, src/views/ProjectPost.vue
=> refactor/projectPost 이후, 바로 ProjectDetail로 이동

src/common/HeaderLayout.vue
- 사용자가 로그인 했을 때만 프로젝트 생성 버튼 랜더링 되도록 변경
=> 헤더 프로젝트 생성 버튼 랜더링 조건 변경

src/common/HeaderLayout.vue
- 검색어 텍스트 색상이 흰색이라 잘 안 보이는 문제 발견
- 검색어 텍스트 색상을 검은색으로 변경
=> Design: 헤더 검색창 텍스트 색상 변경

src/components/MemberCard.vue, src/components/MemberCardList.vue, src/components/ProjectCard.vue
- 멤버 카드를 프로젝트 카드 디자인과 비슷하게 변경
- 프로젝트 카드의 진행 기간 표시를 일(day)에서 주(week)로 변경
- 멤버 카드 리스트의 gap을 15px에서 10px로 변경
=> Design: 멤버 카드, 프로젝트 카드 디자인 수정

src/components/project-detail/LeaderInfo.vue, src/components/project-detail/RecruitmentStatus.vue
- 1:1 채팅 버튼을 커피 챗으로 변경
- 기술 스택 보여주는 UI 수정
- 지원하기 버튼 눌렀을 때 api 요청
=> UI 변경 및 지원하기 버튼 기능 추가

src/common/HeaderLayout.vue, src/components/ProjectManagementCard.vue, src/components/login/TechStackSelector.vue, src/components/project-detail/ProjectManagement.vue
=> feat/memberCard수정,alarm  화면 구성

src/common/HeaderLayout.vue
- 라우트 경로가 정확히 일치해야만 프로젝트 생성 버튼이 활성화되도록 변경
=> Fix: 헤더 프로젝트 생성 UI 변경

src/views/ProjectDetailPage.vue
- 프로젝트 상세 페이지에서 projectId가 존재하지 않는 경우 홈페이지로 리다이렉트
=> Fix: 존재하지 않는 프로젝트 처리

src/views/MainPage.vue
description 부분 삭제
carousel height 줄임
<br>
=> change: 인기 프로젝트 description 부분 삭제

src/common/HeaderLayout.vue, src/components/ProjectManagementCard.vue
=> upDesign/ManageMentCard_애매한 길이 아이디 대응

src/common/HeaderLayout.vue, src/router/route.js, src/views/MainPage.vue
- Header 주석 추가
- 홈페이지 route 경로 변경
- MainPage UI 수정
=> Change: Header, route.js, MainPage 수정

src/common/HeaderLayout.vue, src/components/ProjectCard.vue, src/router/route.js, src/views/MainPage.vue
=> design: 홈페이지 carousel 변경, 헤더에 로그인/로그아웃 줄맞춤

src/socket.js, src/store/modules/projectStore.js, src/views/ProjectPost.vue
=> update/post 후, state 초기화

src/components/MemberCard.vue, src/components/ProjectCard.vue
=> Design: 프로젝트 카드, 멤버 카드에 폰트 적용

src/views/MainPage.vue
=> Design: 메인 페이지 carousel 제목 폰트 변경

src/components/project/ProjectEditor.vue, src/components/project/ProjectTechStack.vue, src/main.js, src/views/ProjectDetailPage.vue
=> Change/ã텍스트에디터 업로드 방식 변경 & ë2ã회씩 마운트 되는 현상 수정

src/components/chat/ChatCompo.vue, src/components/chat/ChatMessage.vue, src/components/chat/ChatModal.vue
채팅 기능 
특정 사용자에게 전송하는 방식에서 room방식으로 변경
메세지 정렬 방식 변경
<br>
=> Change: 전송 방식 room으로 변경

src/common/ContentLayout.vue, src/components/chat/ChatModal.vue, src/store/index.js, src/store/modules/chatStore.js
채팅 기능 구현
해당 채팅방 안보고있을 때 팝업 알람
<br>
=> Feat: chatting alarm

src/components/MemberCard.vue, src/components/MemberCardList.vue
- 멤버 카드 사이즈 270px로 변경
- 멤커 카드 리스트 gap 5px로 변경
=> Change: 멤버 카드 크기 및 gap 사이즈 조정

src/views/SearchAllPage.vue, src/views/SearchMemberPage.vue, src/views/SearchProjectPage.vue
- 모든 검색 결과 페이지의 margin-top을 mt-10으로 설정
=> Design: 검색 결과 페이지 제목 마진 설정

src/components/project-retrospective/ProjectRetrospective.vue
- retrospectiveId -> retId로 변경
=> Change: 회고 수정 axios url 변경

src/components/project-detail/LeaderInfo.vue, src/components/project-detail/RecruitmentStatus.vue, src/store/modules/projectStore.js, src/views/ProjectDetailPage.vue
- 로그인 상태라면 이전에 프로젝트에 지원 했는지 여부와 상관없이 지원 가능함
- 로그인한 상태 && 로그인한 유저가 해당 프로젝트에 지원한 상태가 아니여야만 지원 가능함
=> Change: 프로젝트 지원 버튼 랜더링 조건 변경

src/common/ContentLayout.vue, src/common/HeaderLayout.vue, src/socket.js, src/views/ProjectDetailPage.vue
=> feat: 알람 마무리:

src/components/project-retrospective/ProjectRetrospective.vue
- 회고 탭에서 선택한 멤버와 로그인한 멤버가 같을 때만 회고 작성 및 수정 버튼 랜더링
=> Change: 회고 작성/수정 버튼 랜더링 조건 변경

src/socket.js
=> Fix: 운영 환경 도메인 추가

src/socket.js
=> Fix: 로그 추가

src/components/project-retrospective/ProjectRetrospective.vue
- 회고가 없을 때 '선택한 주차의 회고가 없습니다.`는 문구 추가
=> Change: 회고가 없을 때 메시지 추가

src/views/MainPage.vue
- 커스텀 기술스택 폰트를 기존 폰트에서 caption 폰트로 변경
=> design: 메인페이지 top10 프로젝트의 기술스택 폰트 변경

src/socket.js
=> Fix: 소켓 주소 변경

src/common/ContentLayout.vue
=> Test: access token 프론트에서 쿠키 저장

src/common/ContentLayout.vue
=> ㄱrefactor: 모ë겹ì채팅 모채팅ã모달수정

src/App.vue, src/axiosInstance.js, src/common/ContentLayout.vue, src/common/HeaderLayout.vue, src/components/login/AdditionalInfoModal.vue, src/components/project-detail/ProjectManagement.vue, src/components/project-retrospective/ProjectRetrospective.vue, src/main.js, src/plugins/axios_custom.js, src/store/modules/memberStore.js, src/store/modules/projectStore.js, src/views/MainPage.vue, src/views/MyPage.vue, src/views/SearchAllPage.vue, src/views/SearchProjectPage.vue
토큰 저장 방식 쿠키에서 로컬 스토리지로 변경
<br>
=> Change: 토큰 저장 방식 쿠키에서 로컬 스토리지로 변경

src/plugins/axios_custom.js
=> Fix: 안쓰는 import router 제거

src/store/modules/memberStore.js, src/views/ProjectDetailPage.vue
=> Fix: 로그인 필요한 요청 axiosInstance로 변경 

src/axiosInstance.js, src/plugins/axios_custom.js, src/views/ProjectDetailPage.vue
=> Fix: axiosInstance 변경

src/components/project-retrospective/ProjectRetrospective.vue, src/store/modules/projectStore.js
- 사용자가 로그인을 했을 때만 프로젝트에 참여하고 있는지 확인하는 api 요청 (/api/projects/{projectId}/participation)
- 사용자가 로그인을 했을 때만 프로젝트에 지원했는지 확인하는 api 요청 (/api/projects/{projectId}/applications/status)
=> Change: api 요청 조건 변경

src/components/chat/ChatModal.vue, src/plugins/axios_custom.js, src/socket.js
=> fix_websocket, alarm, TokenParser, RabbitMQ

src/App.vue
=> Fix: access token 전달하면 쿼리스트링에서 삭제

src/socket.js, src/store/modules/memberStore.js
=> refactor:웹소켓 이벤트 중복등록 해결

src/store/modules/memberStore.js
=> fix_alarm조회

src/common/ContentLayout.vue, src/components/chat/ChatModal.vue, src/socket.js
=> feat: 채팅에 RabbitMQ 적용

src/components/chat/ChatModal.vue, src/components/project-detail/LeaderInfo.vue
커피 챗 버튼 - 채팅 모달 연결
커피챗 버튼으로 채팅 모달 열었을 때 로직 수정
<br>
=> Fix: 커피챗 버튼 관련 수정 

src/components/chat/ChatMessage.vue, src/components/chat/ChatModal.vue
- 중복 구독 문제 해결
- 처음 채팅 걸었을 때 오류 수정
- 메세지 디자인 수정 
<br>
=> Fix: 중복 구독 문제 해결 

src/socket.js
socket-url 수정 (/node-api 제거)
<br>
=> fix: socket-url 수정

src/components/MemberCard.vue, src/components/project-detail/LeaderInfo.vue
- 프로젝트 정보탭의 리더 정보, 멤버카드에 경력 추가
=> Design: 리더 정보, 멤버 카드에 경력 추가

src/components/chat/ChatModal.vue
처음 메세지 보낼 때 상대방은 방에 참가 안되는 문제 수정
<br>
=> Fix: 처음 메세지 보낼 때 상대방은 방에 참가 안되는 문제 수정

src/components/project-detail/ProjectManagement.vue
=> fix:project_Start 수정

src/components/project-detail/ProjectManagement.vue
=> project_Start 수정

src/components/project-detail/ProjectManagement.vue, src/views/ProjectDetailPage.vue
=> fix:멤버승인시,  프로젝트 리더 화면에서 즉시 렌더링

src/components/project-detail/ProjectManagement.vue, src/views/ProjectDetailPage.vue
=> 멤버승인시, 프로젝트 리더 화면에서 즉시 렌더링

src/components/project-retrospective/ProjectRetrospective.vue
=> 회고, 관리 렌더링(자신이 만든 프로젝트만 관리탭 볼수있음) 
